# Generated by Django 5.0.3 on 2024-03-23 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=30, verbose_name='Ime')),
                ('prezime', models.CharField(max_length=30, verbose_name='Prezime')),
                ('naziv_opg', models.CharField(max_length=100, verbose_name='Naziv OPG-a')),
                ('adresa', models.CharField(max_length=255)),
                ('telefon', models.IntegerField(verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('milk_product', 'Mliječni proizvodi'), ('fruit_product', 'Voće'), ('vegetables_product', 'Povrće')], max_length=20)),
                ('detail', models.TextField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmapp.farm')),
            ],
        ),
    ]
