# Generated by Django 4.2 on 2024-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('milk_product', 'Milk Product'), ('fruit_product', 'Fruit'), ('vegetables_product', 'Vegetables')], max_length=20),
        ),
    ]
