# Generated by Django 4.2 on 2024-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('milk_product', 'Mliječni proizvodi'), ('fruit_product', 'Voće'), ('vegetables_product', 'Povrće')], max_length=20),
        ),
    ]
