# Generated by Django 4.2 on 2024-03-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='name',
        ),
        migrations.AddField(
            model_name='farm',
            name='adresa',
            field=models.CharField(default='Temporary Address', max_length=255),
        ),
        migrations.AddField(
            model_name='farm',
            name='email',
            field=models.EmailField(default='temporary@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='farm',
            name='email_potvrda',
            field=models.EmailField(default='temporary@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='farm',
            name='ime',
            field=models.CharField(default='dean', max_length=30, verbose_name='Ime'),
        ),
        migrations.AddField(
            model_name='farm',
            name='naziv_opg',
            field=models.CharField(default='neki tamo', max_length=100, verbose_name='Naziv OPG-a'),
        ),
        migrations.AddField(
            model_name='farm',
            name='prezime',
            field=models.CharField(default='hudek', max_length=30, verbose_name='Prezime'),
        ),
        migrations.AddField(
            model_name='farm',
            name='telefon',
            field=models.IntegerField(default=123123, max_length=20, verbose_name='Telefon'),
        ),
    ]
