# Generated by Django 4.2 on 2024-03-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_remove_farm_name_farm_adresa_farm_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='adresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farm',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='farm',
            name='email_potvrda',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='farm',
            name='ime',
            field=models.CharField(max_length=30, verbose_name='Ime'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='naziv_opg',
            field=models.CharField(max_length=100, verbose_name='Naziv OPG-a'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='prezime',
            field=models.CharField(max_length=30, verbose_name='Prezime'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='telefon',
            field=models.IntegerField(max_length=20, verbose_name='Telefon'),
        ),
    ]
