# Generated by Django 4.2 on 2024-03-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0005_alter_farm_adresa_alter_farm_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='telefon',
            field=models.IntegerField(verbose_name='Telefon'),
        ),
    ]
