# Generated by Django 5.0.3 on 2024-03-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0006_alter_farm_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='email_potvrda',
        ),
    ]
