# Generated by Django 5.0.3 on 2024-04-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='telefon',
            field=models.IntegerField(max_length=100, verbose_name='Telefon'),
        ),
    ]
