# Generated by Django 5.0.3 on 2024-04-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_alter_farm_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='telefon',
            field=models.BigIntegerField(verbose_name='Telefon'),
        ),
    ]
