#INITIAL DATA FOR PRODUCT CATEGORY
#replace model name with your if you call it different in models.py
- model: ProductCategory
  pk: 1
  fields:
    name: VOĆE
- model: ProductCategory
  pk: 2
  fields:
    name: POVRĆE
- model: ProductCategory
  pk: 3
  fields:
    name: MLIJEČNI PROIZVODI